version: "3.9"

services:
  jfr:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jfr-merger
    ports:
      - "8080:8080"
    volumes:
      - app_storage:/app/storage
    restart: unless-stopped
    environment:
      - JAVA_OPTS=-Xmx2g -Xms2g -XX:+AlwaysPreTouch -XX:+UseG1GC -XX:MaxGCPauseMillis=5000 -XX:ParallelGCThreads=2 -XX:ConcGCThreads=2 -XX:InitiatingHeapOccupancyPercent=90

volumes:
  app_storage:
